Repository iputapp/lounas, pull requests merged in 2023-09, with the labels that each got.

#78 Feature/Expandable Panel
  public/icons/enlarge.svg
  src/app/test/expand-panel/page.tsx
  src/components/layouts/ExpandablePanel/index.tsx
  src/components/layouts/ExpandablePanel/styles.module.scss
  src/components/lists/PaymentGrid/index.tsx
Labels: component

#97 Feature/Card Full Image
  public/icons/location-on.svg
  public/icons/straight.svg
  public/icons/turn-left.svg
  public/icons/turn-right.svg
  public/icons/turn-sharp-left.svg
  public/icons/turn-sharp-right.svg
  public/icons/turn-slight-left.svg
  public/icons/turn-slight-right.svg
  public/test/route.webp
  src/app/test/card-full/page.tsx
  src/components/cards/CardFull/index.tsx
  src/components/cards/CardFull/styles.module.scss
Labels: component

#50 Feature/Back Button
  public/icons/nav-arrow-left-semibold.svg
  src/app/test/back-button/page.tsx
  src/components/buttons/BackButton/index.tsx
  src/components/buttons/BackButton/styles.module.scss
Labels: component

#83 Feature/Bordered Title
  src/app/test/bordered-title/page.tsx
  src/components/headers/BorderedTitle/index.tsx
  src/components/headers/BorderedTitle/styles.module.scss
Labels: component

#70 Feature/Borderd Circle Button
  src/app/test/bordered-circle-button/page.tsx
  src/components/buttons/BorderdCircleButton/index.tsx
  src/components/buttons/BorderdCircleButton/styles.module.scss
Labels: component

#96 Feature/Bordered Rounded Button
  src/app/test/bordered-rounded-button/page.tsx
  src/components/buttons/BorderedRoundedButton/index.tsx
  src/components/buttons/BorderedRoundedButton/styles.module.scss
Labels: component

#88 Feature/Bottom Navigation Bar
  public/icons/calendar.svg
  public/icons/crown.svg
  public/icons/home.svg
  public/icons/user.svg
  src/app/test/bottom-nav-bar/page.tsx
  src/components/navigations/BottomNavigationBar/index.tsx
  src/components/navigations/Footer.tsx
Labels: component

#98 Feature/Card
  public/test/ramen.webp
  src/app/test/card/page.tsx
  src/components/cards/Card/index.tsx
  src/components/cards/Card/styles.module.scss
Labels: component

#100 Comment out `next-experimental`
  next.config.js
Labels: environment

#102 Cleanup codes of `card` components
  src/app/test/card-hor/page.tsx
  src/components/cards/Card/index.tsx
  src/components/cards/CardHorizontal/index.tsx
  src/components/cards/CardHorizontal/styles.module.scss
Labels: component

#103 Cleanup codes of `BackButton` component
  src/app/test/back-button/page.tsx
  src/components/buttons/BackButton/index.tsx
  src/components/buttons/BackButton/styles.module.scss
Labels: component

#104 Update `eslint` settings
  .eslintrc.json
Labels: environment

#101 Rename `Bordered*` components to `Border*`
  src/app/test/border-circle-button/page.tsx
  src/app/test/border-round-button/page.tsx
  src/app/test/border-title/page.tsx
  src/app/test/bordered-rounded-button/page.tsx
  src/app/test/bordered-title/page.tsx
  src/components/buttons/BorderCircleButton/index.tsx
  src/components/buttons/BorderCircleButton/styles.module.scss
  src/components/buttons/BorderRoundButton/index.tsx
  src/components/buttons/BorderRoundButton/styles.module.scss
  src/components/headers/BorderTitle/index.tsx
  src/components/headers/BorderTitle/styles.module.scss
Labels: component

#56 schema.prisma定義
  package-lock.json
  package.json
  prisma/schema.prisma
Labels: package, security, api route

#106 Define a Prisma schema
  package-lock.json
  package.json
  prisma/schema.prisma
Labels: package, security, api route

#109 Add props to `BorderTitle` component
  src/app/test/border-title/page.tsx
  src/components/headers/BorderTitle/index.tsx
  src/components/headers/BorderTitle/styles.module.scss
Labels: component

#115 Modify bottom navigation bar icon
  public/icons/logo-fill.svg
  public/icons/logo-outline.svg
  src/components/navigations/BottomNavigationBar/index.tsx
Labels: component, icon

#110 Zod validation definition in schema.prisma
  _docs/CODING.md
  package-lock.json
  package.json
  prisma/migrations/20230906084954_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/lib/zod/index.ts
Labels: package, security, api route

#130 Fix the issue of the bottom navigation bar transparent
  src/components/navigations/BottomNavigationBar/index.tsx
Labels: component

#131 Fix `rect-button` more extensible
  src/app/test/rect-button/page.tsx
  src/components/buttons/RectButton/index.tsx
  src/components/buttons/RectButton/styles.module.scss
Labels: component

#133 Enhance the extensibility of the 'border-round-button`
  src/app/test/border-round-button/page.tsx
  src/components/buttons/BorderRoundButton/index.tsx
  src/components/buttons/BorderRoundButton/styles.module.scss
Labels: component

#134 Feature/RootLayout with favicons
  public/favicon/android-chrome-192x192.png
  public/favicon/android-chrome-512x512.png
  public/favicon/apple-touch-icon.png
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/safari-pinned-tab.svg
  public/favicon/site.webmanifest
  public/next.svg
  public/vercel.svg
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/webapp/layout.module.scss
  src/app/webapp/layout.tsx
  src/app/webapp/test/page.tsx
Labels: page, meta

#135 Delete props from `bottom-navigation-bar`
  src/components/navigations/BottomNavigationBar/index.tsx
Labels: component

#116 Feature/Dummy Panel
  src/app/test/dummy/page.tsx
  src/app/test/dummy/test/page.module.scss
  src/app/test/dummy/test/page.tsx
  src/components/layouts/DummyPanel/index.tsx
  src/components/layouts/DummyPanel/styles.module.scss
Labels: component

#140 Cleanup codes
  src/app/loading.tsx
  src/app/signup/layout.tsx
  src/app/signup/otp/layout.tsx
  src/app/signup/page.tsx
  src/app/signup/template.tsx
  src/components/layouts/AnimatePresenceLayer/index.tsx
  src/components/layouts/LoadingLayer/index.tsx
  src/components/layouts/LoadingLayer/styles.module.scss
  src/styles/components/layouts/loading.module.scss
Labels: minor change

#141 Add safe-area sizes to `_variables.scss`
  src/app/dish/layout.module.scss
  src/app/privacy/layout.module.scss
  src/app/recommend/layout.module.scss
  src/app/restaurant/layout.module.scss
  src/app/webapp/layout.module.scss
  src/styles/_variables.scss
Labels: style

#142 Add `$tertiary` color
  src/styles/_variables.scss
Labels: style

#79 Feature/Privacy Page
  public/lottie/privacy-animation.json
  src/app/privacy/page.module.scss
  src/app/privacy/page.tsx
  src/app/test/dialog-info/page.tsx
  src/components/buttons/RectButton/index.tsx
  src/components/buttons/RectButton/styles.module.scss
  src/components/dialogs/DialogInfo/index.tsx
  src/components/lottie/Privacy.tsx
  src/styles/_variables.scss
Labels: page

#143 Cleanup meta-data
  src/app/dish/layout.tsx
  src/app/layout.tsx
  src/app/privacy/layout.tsx
  src/app/recommend/explore/layout.tsx
  src/app/recommend/layout.tsx
  src/app/recommend/result/layout.tsx
  src/app/restaurant/layout.tsx
  src/app/signup/layout.tsx
  src/app/webapp/diary/layout.tsx
  src/app/webapp/home/layout.tsx
  src/app/webapp/layout.tsx
  src/app/webapp/ranking/layout.tsx
  src/app/webapp/user/layout.tsx
Labels: meta

#80 Feature/Error Page
  public/lottie/error-animation.json
  src/app/signup/otp/error.module.scss
  src/app/signup/otp/error.tsx
  src/app/test/error/error.module.scss
  src/app/test/error/page.tsx
  src/app/test/layout.module.scss
  src/app/test/layout.tsx
  src/components/lottie/Error.tsx
Labels: page

#107 Feature/Home Page
  src/app/test/border-circle-button/page.tsx
  src/app/webapp/home/layout.tsx
  src/app/webapp/home/page.module.scss
  src/app/webapp/home/page.tsx
  src/components/backgrounds/CirclesTopLeft/index.tsx
  src/components/backgrounds/CirclesTopLeft/styles.module.scss
  src/components/buttons/BorderCircleButton/index.tsx
  src/components/buttons/BorderCircleButton/styles.module.scss
  src/components/progresses/BasicLinearProgress/index.tsx
  src/styles/_variables.scss
Labels: page

#117 Feature/Recommend Result Page
  src/app/recommend/layout.module.scss
  src/app/recommend/result/page.module.scss
  src/app/recommend/result/page.tsx
  src/app/test/card-hor/page.tsx
  src/components/cards/CardHorizontal/index.tsx
  src/components/cards/CardHorizontal/styles.module.scss
  src/components/lists/Payment/index.tsx
  src/components/lists/PaymentShort/index.tsx
  src/styles/_variables.scss
Labels: page

#145 Cleanup func name of `Recommend Result Page`
  src/app/recommend/result/page.tsx
Labels: page

#120 Feature/Recommend Loading Page
  src/app/recommend/explore/loading/page.module.scss
  src/app/recommend/explore/loading/page.tsx
  src/components/buttons/RectButton/styles.module.scss
  src/components/headers/BorderTitle/index.tsx
Labels: page

#146 Cleanup codes
  src/app/recommend/explore/loading/page.module.scss
  src/app/recommend/explore/loading/page.tsx
  src/app/test/border-title/page.tsx
  src/app/webapp/home/page.tsx
  src/components/headers/BorderTitle/index.tsx
  src/components/headers/BorderTitle/styles.module.scss
  src/components/skeletons/BasicSkeleton/index.tsx
Labels: page, component

#119 Feature/Dish Page
  public/icons/enlarge.svg
  public/icons/expand.svg
  src/app/dish/[id]/.tsx
  src/app/dish/[id]/page.module.scss
  src/app/dish/[id]/page.tsx
  src/app/dish/layout.module.scss
  src/app/test/card/page.tsx
  src/app/test/expand-panel/page.tsx
  src/components/buttons/BackButton/index.tsx
  src/components/buttons/BackButton/styles.module.scss
  src/components/cards/Card/index.tsx
  src/components/cards/Card/styles.module.scss
  src/components/layouts/ExpandablePanel/index.tsx
  src/components/layouts/ExpandablePanel/styles.module.scss
  src/components/lists/PaymentGrid/index.tsx
  src/components/lists/PaymentLong/index.tsx
  src/components/lists/PaymentShort/index.tsx
Labels: page, component

#147 Cleanup font-color
  src/components/cards/Card/styles.module.scss
  src/components/layouts/ExpandablePanel/index.tsx
  src/components/layouts/ExpandablePanel/styles.module.scss
Labels: component

#127 Feature/Calendar Page
  public/mockup/diary.webp
  src/app/webapp/diary/page.module.scss
  src/app/webapp/diary/page.tsx
  src/components/layouts/DummyPanel/index.tsx
  src/components/layouts/DummyPanel/styles.module.scss
  src/components/navigations/BottomNavigationBar/index.tsx
Labels: page, component

#148 Update Dish page
  public/test/katsudon.webp
  src/app/dish/[id]/page.tsx
  src/components/cards/Card/styles.module.scss
  src/components/layouts/ExpandablePanel/index.tsx
  src/components/layouts/ExpandablePanel/styles.module.scss
Labels: page, component

#128 Feature/Restaurant Navigation Page
  public/icons/warning-circle.svg
  public/mockup/map.webp
  public/test/route-2.webp
  src/app/restaurant/[id]/navi/.tsx
  src/app/restaurant/[id]/navi/page.module.scss
  src/app/restaurant/[id]/navi/page.tsx
  src/app/restaurant/layout.module.scss
  src/components/cards/CardFull/index.tsx
  src/components/cards/CardFull/styles.module.scss
Labels: page, component

#149 Rename import name of icon on back-button
  src/components/buttons/BackButton/index.tsx
Labels: component

#150 Update link of bottom-navigation-bar
  src/components/navigations/BottomNavigationBar/index.tsx
Labels: component

#151 Fix icon-color not changing
  src/components/navigations/BottomNavigationBar/index.tsx
Labels: component

#138 Feature/User Page
  public/icons/github.svg
  public/icons/instagram.svg
  public/icons/lock.svg
  public/icons/twitter.svg
  src/app/webapp/user/layout.tsx
  src/app/webapp/user/page.tsx
  src/app/webapp/user/signin/page.module.scss
  src/app/webapp/user/signin/page.tsx
  src/app/webapp/user/signout/page.module.scss
  src/app/webapp/user/signout/page.tsx
  src/components/backgrounds/TrianglesCover/index.tsx
  src/components/backgrounds/TrianglesCover/styles.module.scss
  src/components/buttons/BorderRoundButton/styles.module.scss
  src/components/layouts/DummyPanel/styles.module.scss
Labels: page, component

#69 Feature/Circle Button
  src/app/test/circle-button/constants.ts
  src/app/test/circle-button/page.tsx
  src/app/test/circle-button/price/page.tsx
  src/app/test/circle-button/quantity/page.tsx
  src/app/test/circle-button/result/page.tsx
  src/app/test/circle-button/taste/page.tsx
  src/app/test/circle-button/template.module.scss
  src/app/test/circle-button/template.tsx
  src/components/buttons/CircleButton/index.tsx
  src/components/buttons/CircleButton/styles.module.scss
Labels: component

#99 Feature/Selection Stack
  src/app/test/circle-button/template.module.scss
  src/app/test/circle-button/template.tsx
  src/components/widgets/SelectionStack/index.tsx
  src/components/widgets/SelectionStack/styles.module.scss
Labels: component

#153 Update logo design
  public/favicon/android-chrome-192x192.png
  public/favicon/android-chrome-512x512.png
  public/favicon/apple-touch-icon.png
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/safari-pinned-tab.svg
  public/icons/logo-full-color.svg
  public/icons/logo-outline-color.svg
  src/app/favicon.ico
  src/components/layouts/DummyPanel/index.tsx
  src/components/layouts/DummyPanel/styles.module.scss
Labels: component, icon

#154 Feature/Recommend Explore Page
  src/app/recommend/explore/(attributes)/constants.ts
  src/app/recommend/explore/(attributes)/loading/page.module.scss
  src/app/recommend/explore/(attributes)/loading/page.tsx
  src/app/recommend/explore/(attributes)/price/page.module.scss
  src/app/recommend/explore/(attributes)/price/page.tsx
  src/app/recommend/explore/(attributes)/quantity/page.module.scss
  src/app/recommend/explore/(attributes)/quantity/page.tsx
  src/app/recommend/explore/(attributes)/taste/page.module.scss
  src/app/recommend/explore/(attributes)/taste/page.tsx
  src/app/recommend/explore/(attributes)/template.tsx
  src/app/recommend/explore/(attributes)/test.ts
  src/app/recommend/explore/page.tsx
  src/app/recommend/explore/template.tsx
  src/components/buttons/BackButton/index.tsx
  src/components/buttons/CircleButton/index.tsx
Labels: page, component

#155 Feature/Ranking Page (Mockup)
  public/mockup/ranking.webp
  src/app/webapp/ranking/page.module.scss
  src/app/webapp/ranking/page.tsx
Labels: page

#156 Update/Diary Page (Mockup)
  public/mockup/diary.webp
  src/app/webapp/diary/page.tsx
Labels: page

#157 Update/Dummy Panel
  src/app/webapp/diary/page.module.scss
  src/app/webapp/ranking/page.module.scss
  src/components/layouts/DummyPanel/index.tsx
  src/components/layouts/DummyPanel/styles.module.scss
Labels: component

#159 Bump packages
  package-lock.json
  package.json
  src/app/page.tsx
  src/lib/zod/index.ts
  src/middleware.ts
Labels: package

#160 [MUI] Add theme to change font-family
  src/components/dialogs/DialogInfo/index.tsx
  src/styles/mui.ts
Labels: style, component
