Repository iputapp/lounas, pull requests merged in 2023-08, with the labels that each got.

#31 Add `github-template`
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/features.md
  .github/PULL_REQUEST_TEMPLATE/features.md
Labels: documentation

#32 Fix `github-templates`
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/task-feature.md
  .github/PULL_REQUEST_TEMPLATE/task-feature.md
Labels: documentation

#34 Add PR instructions to README.md
  README.md
Labels: documentation

#53 Prisma-install
  package-lock.json
  package.json
  prisma/schema.prisma
  src/lib/prisma.ts
Labels: package

#55 Bump packages
  package-lock.json
  package.json
Labels: package

#57 Update code checking to be more strict
  .eslintrc.json
  prettier.config.js
Labels: environment

#59 Fix errors from ESLint
  .eslintignore
  .eslintrc.json
Labels: environment

#60 Add rules to `next-config`
  next.config.js
Labels: environment

#62 Fix import statement #61
  next.config.js
Labels: environment

#66 Update GitHub templates
  .github/ISSUE_TEMPLATE/task-feature.md
  .github/PULL_REQUEST_TEMPLATE/task-feature.md
Labels: documentation

#67 Update documents
  _docs/CODING.md
  _docs/DIRECTORY.md
Labels: documentation

#68 Add colors
  src/styles/_variables.scss
Labels: style

#72 Update DIRECTORY.md
  _docs/DIRECTORY.md
Labels: documentation

#64 Feature/RectButton
  src/app/test/rect-button/page.tsx
  src/components/buttons/RectButton/index.tsx
  src/components/buttons/RectButton/styles.module.scss
Labels: component

#43 Feature/Dialog Info
  public/icons/arrowtriangle.right.fill.svg
  public/icons/nav-arrow-down.svg
  public/icons/nav-arrow-left.svg
  public/icons/nav-arrow-right.svg
  public/icons/nav-arrow-up.svg
  src/app/test/dialog-info/page.module.scss
  src/app/test/dialog-info/page.tsx
  src/components/dialogs/DialogInfo/index.tsx
Labels: component

#82 Delete SF Symbols icons #81
  public/icons/calendar.svg
  public/icons/crown.svg
  public/icons/house.svg
  public/icons/person.svg
Labels: icon
