Repository iputapp/lounas, pull requests merged in 2024-06, with the labels that each got.

#285 chore(vercel): build ignore settings
  vercel-build-ignore.sh
  vercel.json
Labels: Feature: New, Type: CI/CD

#286 refactor(path): define paths for constants
  src/app/(pages)/signup/(otp)/verify/page.tsx
  src/app/(pages)/tos/page.tsx
  src/app/(root)/mobile/page.tsx
  src/app/(root)/page.tsx
  src/app/webapp/user/signout/constants.tsx
  tsconfig.json
Labels: Feature: Refactoring

#287 chore(docs): corrected link references
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/SECURITY.md
Labels: Type: Documentation

#283 アンケートポップアップを追加
  public/images/survey-banner.jpg
  src/app/webapp/home/page.module.scss
  src/app/webapp/home/page.tsx
Labels: Feature: New

#288 release(deploy): アンケートポップアップ
  public/images/survey-banner.jpg
  src/app/webapp/home/page.module.scss
  src/app/webapp/home/page.tsx
Labels: Type: Release, Feature: New
